+incdir+$ip/src/rtl/psoc_rtl/psoc/rtl
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_cfg_addr_pkg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_rtl_pkg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/sbr_rtl_pkg.v
$ip/src/rtl/psoc_rtl/sbb/rtl/sbb_rtl_pkg.sv
$ip/src/rtl/psoc_rtl/dfx_agg/rtl/dfxagg_rtl_pkg.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/tb_psoc_parc_ic_wrap.v
$ip/src/rtl/psoc_rtl/psoc/rtl/die_id_is_io_die0.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_ctech_or_reduce.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/sw_mailbox_cfg_reg_pkg.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/sw_mailbox_cfg_reg_if.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_reset_conf_reg_if.sv
$ip/src/rtl/psoc_rtl/io/rtl/jgsio_gpio.v
$ip/src/rtl/psoc_rtl/io/rtl/io_mux.v
$ip/src/rtl/psoc_rtl/io/rtl/giolgc_gf_top.sv
$ip/src/rtl/psoc_rtl/cmsdk_ahb_gpio/rtl/cmsdk_ahb_gpio_top.v
$ip/src/rtl/psoc_rtl/cmsdk_ahb_gpio/rtl/cmsdk_ahb_gpio.v
$ip/src/rtl/psoc_rtl/cmsdk_ahb_gpio/rtl/cmsdk_ahb_to_iop.v
$ip/src/rtl/psoc_rtl/cmsdk_iop_gpio/rtl/cmsdk_iop_gpio.v
$ip/src/rtl/psoc_rtl/cmsdk_ahb_timeout_mon/rtl/cmsdk_ahb_timeout_mon.v
$ip/src/rtl/psoc_rtl/boot_man/rtl/grad_rst.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_reset_conf_reg_wrap.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_reset_regs_to_structs.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_reset_iso_ctrl.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_logic.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_pkg.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_logic.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_intr_ctrl.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_axi_arb.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_mst.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_slv.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_replay_buffer.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_tx.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_tx_arb.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_tx_dw_wrap.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_rx_dw_wrap.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_rx.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_rx_fork.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_ecc_gen.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_ecc_check.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_ecc_ovrd.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_cfg_reg.v
$ip/src/rtl/psoc_rtl/d2d_spi/rtl/d2d_spi_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_access_prot_wrap.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_ic_id_compress.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_gpio_ctrl.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_axi_addr_dec.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_axi_split_top_wrap.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_axi_split_mem_pipe_2p.v
+incdir+$ip/src/rtl/psoc_rtl/psoc/mem_wrap/inc
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_axi_split1_mem_wrap_a8x8_2p.v
$ip/src/rtl/psoc_rtl/cmsdk_apb_timer/rtl/cmsdk_apb_timer.v
$ip/src/rtl/psoc_rtl/cmsdk_apb_timer/rtl/cmsdk_apb_timer_top.v
$ip/src/rtl/psoc_rtl/cmsdk_apb_uart/rtl/cmsdk_apb_uart.v
$ip/src/rtl/psoc_rtl/cmsdk_apb_uart/rtl/cmsdk_apb_uart_top.v
$ip/src/rtl/psoc_rtl/cmsdk_apb_watchdog/rtl/cmsdk_apb_watchdog_defs.v
$ip/src/rtl/psoc_rtl/cmsdk_apb_watchdog/rtl/cmsdk_apb_watchdog_frc.v
$ip/src/rtl/psoc_rtl/cmsdk_apb_watchdog/rtl/cmsdk_apb_watchdog.v
$ip/src/rtl/psoc_rtl/cmsdk_apb_watchdog/rtl/cmsdk_apb_watchdog_top.v
+incdir+$ip/src/rtl/psoc_rtl/cmsdk_apb_watchdog/rtl
$ip/src/rtl/psoc_rtl/psoc/rtl/global_conf_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/global_conf_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_global_conf2_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_global_conf2_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/i2c_top.v
$ip/src/rtl/psoc_rtl/psoc/rtl/apb_to_i2c.v
$ip/src/rtl/psoc_rtl/psoc/rtl/spi_top.v
$ip/src/rtl/psoc_rtl/psoc/rtl/spi_semaphore.v
$ip/src/rtl/psoc_rtl/psoc/rtl/apb_to_spi.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_spi_init.v
$ip/src/rtl/psoc_rtl/boot_man/rtl/bmn_rst_cfg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/qspi_top.v
$ip/src/rtl/psoc_rtl/psoc/rtl/apb_to_qspi.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_qspi_init.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_qspi_ex_init.v
+incdir+$ip/src/rtl/psoc_rtl/qspi/rtl
$ip/src/rtl/psoc_rtl/qspi/cell_override/qspi_DW_def.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_cc_constants.vh
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_all_includes.vh
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi-undef.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_bcm00_ck_inv.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_bcm06.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_bcm21.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_bcm36_nhs.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_bcm57.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_bcm_params.vh
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_biu.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_fifo.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_intctl.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_mstfsm.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_qstc.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_regfile.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_rxsr.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_sclkgen.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_shift.v
$ip/src/rtl/psoc_rtl/qspi/rtl/qspi_DW_apb_ssi_txsr.v
$ip/src/rtl/psoc_rtl/mem_copy/rtl/mem_copy.v
$ip/src/rtl/psoc_rtl/mem_copy/rtl/mem_copy_cfg_reg.v
$ip/src/rtl/psoc_rtl/mem_copy/rtl/mem_copy_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/mem_copy/rtl/mem_copy_core.v
$ip/src/rtl/psoc_rtl/boot_seq/rtl/boot_seq.v
$ip/src/rtl/psoc_rtl/boot_seq/rtl/btl_rom.v
$ip/src/rtl/psoc_rtl/boot_seq/rtl/boot_seq_auto_config.v
$ip/src/rtl/psoc_rtl/btl/rtl/btl.v
$ip/src/rtl/psoc_rtl/btl/rtl/btl_top.v
$ip/src/rtl/psoc_rtl/btl/rtl/btl_cfg_reg.v
$ip/src/rtl/psoc_rtl/btl/rtl/btl_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/btl/rtl/crc32_dat32_flat.v
$ip/src/rtl/psoc_rtl/psoc/rtl/boot_conf_and_sec_cfg_reg_if.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/boot_conf_and_sec_cfg_reg_wrap.sv
$ip/src/rtl/psoc_rtl/generic_ic/rtl/psoc_boot_wrap_cfg_reg_fork.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_security_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_security_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_boot_conf_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_boot_conf_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/non_rst_flops.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_generic_counter.v
$ip/src/rtl/psoc_rtl/boot_man/rtl/bmn_rst_cfg_w_inc.v
$ip/src/rtl/psoc_rtl/boot_man/rtl/cold_rst_config.sv
$ip/src/rtl/psoc_rtl/boot_man/rtl/security_cpu_start_config.sv
$ip/src/rtl/psoc_rtl/boot_man/rtl/security_efuse_config.sv
$ip/src/rtl/psoc_rtl/boot_man/rtl/security_pll_en_config.sv
$ip/src/rtl/psoc_rtl/boot_man/rtl/security_pll_lock_check.sv
$ip/src/rtl/psoc_rtl/boot_man/rtl/security_pll_switch.sv
$ip/src/rtl/psoc_rtl/boot_man/rtl/boot_man.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_timeout_logic.v
$ip/src/rtl/psoc_rtl/psoc_boot_wrap/rtl/psoc_boot_wrap.v
$ip/src/rtl/psoc_rtl/psoc_boot_wrap/rtl/psoc_boot_wrap_apb_ic.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/gpio_err_ctrl.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_residency_counter.v
+incdir+$ip/src/rtl/psoc_rtl/boot_man/rtl/new_boot
$ip/src/rtl/psoc_rtl/boot_man/rtl/new_boot/new_boot_man_cdc_and_smp.sv
$ip/src/rtl/psoc_rtl/boot_man/rtl/new_boot/new_boot_man_edge_detector.sv
$ip/src/rtl/psoc_rtl/boot_man/rtl/new_boot/new_boot_man_old_fsm.sv
$ip/src/rtl/psoc_rtl/boot_man/rtl/boot_man_fsm.sv
$ip/src/rtl/psoc_rtl/boot_man/rtl/new_boot/new_boot_man.sv
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_cfg_reg.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_top.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_clock_gen.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_trigger_gen.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_mdata_cmd_gen.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_mdata_gen.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_sdata_rec.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_re_sync_pulse_gen.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_re_sync_ctrl.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_bus_ctrl.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/avs_bus.v
$ip/src/rtl/psoc_rtl/avs_bus/rtl/hl_crc_d29_pb_l0_avs.v
$ip/src/rtl/psoc_rtl/smi/rtl/smi.v
$ip/src/rtl/psoc_rtl/psoc/rtl/rst_ctrl_wrap.v
$ip/src/rtl/psoc_rtl/psoc/rtl/semaphore_wrap.v
$ip/src/rtl/psoc_rtl/i2c_slv/rtl/i2c_slv_top.v
$ip/src/rtl/psoc_rtl/i2c_slv/rtl/i2c_slv.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_ic_top_wrap.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_psoc_hbw_lbw_split.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_psoc_lbw_mem_split_wrap.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_psoc_lbw_mem_split.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_psoc_gw.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_psoc_lbw_gw.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_ic_arb.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_psoc_mem_128.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_psoc_mem_32.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_psoc_lbw_dbg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_apb2ahb.v
$ip/src/rtl/psoc_rtl/psoc/rtl/sw_mailbox_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/sw_mailbox_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/sw_mailbox_cfg_reg_wrap.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/hw_mailbox_x8_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/hw_mailbox_x8_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_gen_ic_axi_shrink_rd_mem_pipe_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_gen_ic_axi_shrink_rd1_mem_wrap_a8x8_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_gen_ic_axi_shrink_rd2_mem_wrap_a8x8_2p.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_axi_cfg_term.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/psoc_cfg_cfg_reg_fork.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_fw_mailbox_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_fw_mailbox_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_coresight.v
$ip/src/rtl/psoc_rtl/psoc/rtl/cs_psoc_trace.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_axi_dap_hat_arb_mux.v
$ip/src/rtl/psoc_rtl/psoc/rtl/cs_dap.v
$ip/src/rtl/psoc_rtl/cs_rom_tables/rtl/cs_apbic_top.v
$ip/src/rtl/psoc_rtl/psoc/rtl/cs_trace_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/cs_trace_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/parc/rtl/parc_axid_ovrd.v
$ip/src/rtl/psoc_rtl/pwm/rtl/pwm_quad.v
$ip/src/rtl/psoc_rtl/pwm/rtl/pwm.v
$ip/src/rtl/psoc_rtl/pwm/rtl/pwm_cfg_reg.v
$ip/src/rtl/psoc_rtl/pwm/rtl/pwm_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/svid/rtl/svid_cfg_reg.v
$ip/src/rtl/psoc_rtl/svid/rtl/svid_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/svid/rtl/svid_fsm.v
$ip/src/rtl/psoc_rtl/svid/rtl/svid_top.v
$ip/src/rtl/psoc_rtl/svid/rtl/svid_clock_gen.v
$ip/src/rtl/psoc_rtl/svid/rtl/svid_trigger_gen.v
$ip/src/rtl/psoc_rtl/svid/rtl/svid_mdata_gen.v
$ip/src/rtl/psoc_rtl/svid/rtl/svid_sdata_rec.v
$ip/src/rtl/psoc_rtl/svid/rtl/svid_ctrl.v
$ip/src/rtl/psoc_rtl/svid/rtl/svid.v
$ip/src/rtl/psoc_rtl/efuse/rtl/efuse_gw.v
$ip/src/rtl/psoc_rtl/efuse/rtl/efuse_cfg_reg.v
$ip/src/rtl/psoc_rtl/efuse/rtl/efuse_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/efuse/rtl/efuse_puller_sol_brg.sv
$ip/src/rtl/psoc_rtl/efuse/rtl/fuse_storage_reg.sv
$ip/src/rtl/psoc_rtl/efuse/rtl/jgs_dfxagg_fuse_storage_wrapper.sv
$ip/src/rtl/psoc_rtl/efuse/rtl/fuse_delivery_fsm.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_scratchpad_sram.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_mem_init.v
$ip/src/rtl/psoc_rtl/rpm/rtl/rpm.v
$ip/src/rtl/psoc_rtl/rpm/rtl/rpm_cfg_reg.v
$ip/src/rtl/psoc_rtl/rpm/rtl/rpm_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/adc/rtl/ext_adc_if.v
$ip/src/rtl/psoc_rtl/adc/rtl/ext_adc_if_core.v
$ip/src/rtl/psoc_rtl/adc/rtl/cs_ctrl_adc_if_core.v
$ip/src/rtl/psoc_rtl/adc/rtl/generic_adc_if_core.v
$ip/src/rtl/psoc_rtl/psoc/rtl/asif_mstr_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/asif_mstr_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_mailbox_wrap.v
$ip/src/rtl/psoc_rtl/psoc/rtl/lbw_attr_ctrl.v
$ip/src/rtl/psoc_rtl/psoc/rtl/lbw_attr_ctrl_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/lbw_attr_ctrl_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_intr_sync.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_error_aggr.v
$ip/src/rtl/psoc_rtl/psoc/rtl/viral_aggr_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/viral_aggr_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/caterr_aggr_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/caterr_aggr_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/boot_seq/rtl/btl_rom_auto_ctrl.v
$ip/src/rtl/psoc_rtl/psoc/rtl/auto_ctrl_wrap_external.v
$ip/src/rtl/psoc_rtl/boot_seq/rtl/btl_rom_ac_cfg_reg.v
$ip/src/rtl/psoc_rtl/boot_seq/rtl/btl_rom_ac_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/dphy_fsm/rtl/dphy_fsm.v
$ip/src/rtl/psoc_rtl/psoc_arc_wrap/rtl/psoc_arc_wrap.v
$ip/src/rtl/psoc_rtl/psoc_arc_wrap/rtl/psoc_arc_ic_wrap.v
$ip/src/rtl/psoc_rtl/psoc_arc_wrap/rtl/arc_addr_mnpl.v
$ip/src/rtl/psoc_rtl/psoc_arc_wrap/rtl/arc_local_conf_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc_arc_wrap/rtl/arc_local_conf_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/arc_dbg_cfg_reg_fork.v
$ip/src/rtl/psoc_rtl/psoc_arc_wrap/rtl/psoc_arc_wrap_cfg_reg_fork.v
$ip/src/rtl/psoc_rtl/psoc_arc_wrap/rtl/ic_top_psoc_arc_wrap.v
$ip/src/rtl/psoc_rtl/psoc_arc_wrap/rtl/ic_top_psoc_arc_arb.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_rst_arc_axi_drain_hbw_wr_mem_pipe_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_rst_arc_axi_drain_hbw_wr1_mem_wrap_a57x16_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_rst_arc_axi_drain_hbw_rd_mem_pipe_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_rst_arc_axi_drain_hbw_rd1_mem_wrap_a57x16_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_rst_arc_axi_drain_lbw_wr_mem_pipe_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_rst_arc_axi_drain_lbw_wr1_mem_wrap_a32x128_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_rst_arc_axi_drain_lbw_rd_mem_pipe_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/psoc_rst_arc_axi_drain_lbw_rd1_mem_wrap_a32x128_2p.v
$ip/src/rtl/psoc_rtl/timestamp_counter/rtl/timestamp_counter.v
+incdir+$ip/src/rtl/psoc_rtl/subIP/jgs.dteg_security_dfxagg/src/rtl/common
+incdir+$ip/src/rtl/psoc_rtl/subIP/jgs.dteg_security_dfxagg/src/rtl/include/JGS
$ip/src/rtl/psoc_rtl/dfx_agg/rtl/jgs_dfxagg_top.sv
$ip/src/rtl/psoc_rtl/dfx_agg/rtl/dfx_agg_apb2reg.sv
$ip/src/rtl/psoc_rtl/ucie_stag/rtl/ucie_stag_fsm.sv
$ip/src/rtl/psoc_rtl/psoc/rtl/lbw_addr_check_modules.v
+incdir+$ip/src/rtl/psoc_rtl/subIP/jgs.sbb_sbbv5/src/rtl/include
+incdir+$ip/src/rtl/psoc_rtl/subIP/jgs.trng_dwc/src
$ip/src/rtl/psoc_rtl/sbb/rtl/interfaces/sbb_mem_if.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/interfaces/efuse_if.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/interfaces/axi_if.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/interfaces/apb_if.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/interfaces/sbb_trng_if.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/sbb_memories.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/sbbv5_wrap.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/sbb_axi_adapter.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/sbb_axi_adapter_id_remmaper.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/sbb_axi_adapter_burst_deaggregator.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/sbb_axi_adapter_cdc.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/sbb_top.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/trng_sbb_fsm.sv
$ip/src/rtl/psoc_rtl/sbb/rtl/sbb_fuse_shim.sv
$ip/src/rtl/psoc_rtl/efuse/rtl/jgs_sbb_fuse_storage_wrapper.sv
$ip/src/rtl/psoc_rtl/parc/rtl/parc_logic.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_hbw_mst_axi_shrink_rd_mem_pipe_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_hbw_mst_axi_shrink_rd1_mem_wrap_a8x8_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_hbw_mst_axi_shrink_rd2_mem_wrap_a8x8_2p.v
$ip/src/rtl/psoc_rtl/parc/rtl/parc_cfg_cfg_reg_fork.v
$ip/src/rtl/psoc_rtl/parc/rtl/parc_if.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_parc_hbw_arb.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_parc_mem.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_parc_lbw.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_parc_mem_arc.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_parc_hbw_cbu.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_parc_lbw_lbu.v
$ip/src/rtl/psoc_rtl/generic_ic/rtl/ic_top_parc_sbb_gw.v
$ip/src/rtl/psoc_rtl/parc/rtl/parc_ic_top_wrap.v
$ip/src/rtl/psoc_rtl/parc/rtl/parc_global_conf_cfg_reg.v
$ip/src/rtl/psoc_rtl/parc/rtl/parc_global_conf_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/parc/rtl/parc_local_cfg_cfg_reg.v
$ip/src/rtl/psoc_rtl/parc/rtl/parc_local_cfg_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/parc/rtl/parc_sai_cfg_reg.v
$ip/src/rtl/psoc_rtl/parc/rtl/parc_sai_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_fw_sram_spi_dma_wrap.v
$ip/src/rtl/psoc_rtl/psoc/rtl/hl_crc_d32_p104c11db7_l0_spi_dma.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_spi_init_new_dma.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_dma_qe_init.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_spi_dma.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_read_terminator.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_bootrom_wrap.v
$ip/src/rtl/psoc_rtl/psoc/rtl/psoc_bootrom.v
$ip/src/rtl/psoc_rtl/parc/rtl/psoc_punit.v
$ip/src/rtl/psoc_rtl/parc/rtl/punit_cfg_reg.v
$ip/src/rtl/psoc_rtl/parc/rtl/punit_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/punit_mem_mem_pipe_1p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/punit_mem1_mem_wrap_a32x1024_1p.v
$ip/src/rtl/psoc_rtl/psoc/rtl/ggtt_scrb.v
$ip/src/rtl/psoc_rtl/psoc/rtl/ggtt_scrb_input.v
$ip/src/rtl/psoc_rtl/psoc/rtl/ggtt_scrb_rd_fsm.v
$ip/src/rtl/psoc_rtl/psoc/rtl/ggtt_scrb_wr_fsm.v
$ip/src/rtl/psoc_rtl/psoc/rtl/ggtt_scrb_cfg_reg.v
$ip/src/rtl/psoc_rtl/psoc/rtl/ggtt_scrb_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_axi_drain_hbw_wr_mem_pipe_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_axi_drain_hbw_wr1_mem_wrap_a57x64_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_axi_drain_hbw_rd_mem_pipe_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_axi_drain_hbw_rd1_mem_wrap_a57x32_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_axi_drain_lbw_wr_mem_pipe_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_axi_drain_lbw_wr1_mem_wrap_a32x128_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_axi_drain_lbw_rd_mem_pipe_2p.v
$ip/src/rtl/psoc_rtl/psoc/mem_wrap/rtl/parc_axi_drain_lbw_rd1_mem_wrap_a32x32_2p.v
$ip/src/rtl/psoc_rtl/w2m/inc/w2m_pkg.v
$ip/src/rtl/psoc_rtl/m2w/rtl/m2w.v
$ip/src/rtl/psoc_rtl/m2w/rtl/m2w_sub_wrap.v
$ip/src/rtl/psoc_rtl/m2w/rtl/m2w_8_cfg_reg.v
$ip/src/rtl/psoc_rtl/m2w/rtl/m2w_8_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/m2w/rtl/m2w_512_cfg_reg.v
$ip/src/rtl/psoc_rtl/m2w/rtl/m2w_512_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/m2w/rtl/m2w_cfg_reg.v
$ip/src/rtl/psoc_rtl/m2w/rtl/m2w_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/w2m/rtl/w2m.v
$ip/src/rtl/psoc_rtl/w2m/rtl/w2m_msg_gen.v
$ip/src/rtl/psoc_rtl/w2m/rtl/w2m_msg_cfg_cfg_reg.v
$ip/src/rtl/psoc_rtl/w2m/rtl/w2m_msg_cfg_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/w2m/rtl/w2m_int_map.v
$ip/src/rtl/psoc_rtl/w2m/rtl/w2m_int_cfg_cfg_reg.v
$ip/src/rtl/psoc_rtl/w2m/rtl/w2m_int_cfg_cfg_reg_fields.v
$ip/src/rtl/psoc_rtl/w2m/rtl/w2m_cfg_cfg_reg.v
$ip/src/rtl/psoc_rtl/w2m/rtl/w2m_cfg_cfg_reg_fields.v
+incdir+$ip/src/rtl/psoc_rtl/subIP/jgs.i3c_dwc/src
$ip/src/rtl/psoc_rtl/i3c_top/rtl/i3c_flop_mem.sv
$ip/src/rtl/psoc_rtl/i3c_top/rtl/i3c_top.sv
